from app.automation.automation_engine import AutomationEngine


class PlanExecutor:
    """
    Executes a Plan generated by PlannerEngine.
    """

    def __init__(self):

        self.automation = AutomationEngine()

        self.automation.initialize()

    def execute(self, plan):

        results = []

        for task in plan:

            result = self.execute_task(task)

            results.append(result)

        return results

    def execute_task(self, task):

        # ---------------- Open Applications ----------------

        if task.action == "open_app":

            if task.target == "notepad":

                self.automation.open_notepad()

                return "Opened Notepad"

            elif task.target == "calculator":

                self.automation.open_calculator()

                return "Opened Calculator"

            elif task.target == "paint":

                self.automation.open_paint()

                return "Opened Paint"

            elif task.target == "cmd":

                self.automation.open_cmd()

                return "Opened CMD"

            else:

                return f"Unknown application: {task.target}"

        # ---------------- AI Chat ----------------

        elif task.action == "chat":

            return "Forward to AI"

        return "Unknown Task"