from app.automation.command_executor import CommandExecutor


class PlanExecutor:
    """
    Executes plans generated by PlannerEngine.
    """

    def __init__(self):

        self.executor = CommandExecutor()

    def execute(self, plan):

        results = []

        for task in plan:

            results.append(
                self.execute_task(task)
            )

        return results

    def execute_task(self, task):

        if task.action == "open_app":

            return self.executor.execute(
                f"open {task.target}"
            )

        elif task.action == "chat":

            return "Forward to AI"

        return "Unknown Task"